### ISSUE TITLE
Entity 수정

### ISSUE THREAD

**Issue by chaewss** [chaewss/chaewsstore#20]
## Description
엔티티 관련 수정

## Todo
- [x] 필요한 엔티티에 isDeleted 필드 추가
- [x] Brand 엔티티 추가
- [x] 관련 연관관계 추가
- [x] equals(), hashCode() 메서드 재정의
