### ISSUE TITLE
주문 기능 구현

### ISSUE THREAD

**Issue by chaewss** [chaewss/chaewsstore#37]
## Description
주문 관련 기능 구현
[[Spring Boot] 동시성 문제 해결하기](https://chaewsscode.tistory.com/242)
[[Spring Boot] 멀티스레드 테스트에서 @Transactional 사용 시 실패하는 이유](https://chaewsscode.tistory.com/243)

## Todo
- [x] 입찰 즉시 구매 · 판매 기능 구현 API 구현
- [x] 입찰 검수 API 구현
- [x] 입찰 금액 입금 API 구현
- [x] 테스트 코드 작성
- [x] docs 작성
