### ISSUE TITLE
테스트 코드 추가

### ISSUE THREAD

**Issue by chaewss** [chaewss/chaewsstore#41]
## Description
누락된 테스트 코드 추가

## Todo
- [x] 누락 테스트 코드 추가
- [x] `@nested` 어노테이션으로 테스트 정리 
- [x] Test Fixture 추가
[[JUnit] 테스트 코드에 Test Fixture 사용하기: 테스트 데이터 재사용](https://chaewsscode.tistory.com/253)
- [x] 집계된 커버리지 보고서 기준 빌드 검증
[멀티모듈 JaCoCo 집계된 커버리지 보고서를 기준으로 빌드 검증](https://chaewsscode.tistory.com/252)
